from collections import defaultdict
from datetime import datetime


class RuleEngine:
    """
    Rule-based detection engine.

    The RuleEngine evaluates structured authentication events against
    predefined detection rules. Each rule represents a specific type
    of suspicious behavior.

    Important:
    This version uses the timestamp extracted from the log entry itself
    rather than the current processing time. This makes the detection
    logic reproducible and suitable for historical log analysis.
    """

    def __init__(self):
        """
        Initializes the rule engine and its internal event storage.
        """

        # Brute-force rule:
        # Trigger if 5 failed login attempts from the same IP address
        # occur within 60 seconds.
        self.bruteforce_threshold = 5
        self.bruteforce_timeframe = 60

        # Repeated failed authentication rule:
        # Trigger if 3 failed login attempts for the same username
        # occur within 120 seconds.
        self.repeated_failed_threshold = 3
        self.repeated_failed_timeframe = 120

        # IP-based login analysis:
        # Trigger if one IP address attempts authentication
        # for 3 different usernames within 120 seconds.
        self.ip_user_threshold = 3
        self.ip_user_timeframe = 120

        # Suspicious login time rule:
        # Successful logins outside this time range are considered suspicious.
        self.allowed_login_start_hour = 6
        self.allowed_login_end_hour = 22

        # Stores failed login events grouped by source IP address.
        self.failed_events_by_ip = defaultdict(list)

        # Stores failed login events grouped by username.
        self.failed_events_by_user = defaultdict(list)

        # Stores attempted usernames grouped by source IP address.
        self.usernames_by_ip = defaultdict(list)

    def process(self, log):
        """
        Processes a structured log event.

        Each valid authentication event is evaluated against all
        implemented detection rules.

        Parameters:
            log (dict):
                Structured event generated by the parser.
        """

        # Only authentication logs are relevant for this prototype.
        if log.get("log_type") != "auth":
            return

        # A valid timestamp is required for all time-based rules.
        if not log.get("timestamp"):
            return

        # Apply all implemented detection rules.
        self.detect_bruteforce(log)
        self.detect_repeated_failed_attempts(log)
        self.detect_ip_based_login_analysis(log)
        self.detect_suspicious_login(log)

    def detect_bruteforce(self, log):
        """
        Detects brute-force attacks.

        A brute-force attack is represented as multiple failed login
        attempts from the same IP address within a short time window.
        """

        if log.get("event_type") != "ssh_failed_login":
            return

        ip = log.get("ip")

        if not ip:
            return

        # Use the actual occurrence time extracted from the log entry.
        event_time = log["timestamp"]

        # Store the failed login attempt for this IP address.
        self.failed_events_by_ip[ip].append({
            "timestamp": event_time,
            "log": log
        })

        # Remove failed login attempts outside the time window.
        self.failed_events_by_ip[ip] = self.cleanup_events(
            events=self.failed_events_by_ip[ip],
            current_time=event_time,
            timeframe=self.bruteforce_timeframe
        )

        if len(self.failed_events_by_ip[ip]) >= self.bruteforce_threshold:
            self.generate_alert(
                rule_name="Brute-force attack detection",
                description=(
                    f"{len(self.failed_events_by_ip[ip])} failed login "
                    f"attempts from the same IP within "
                    f"{self.bruteforce_timeframe} seconds"
                ),
                log=log
            )

    def detect_repeated_failed_attempts(self, log):
        """
        Detects repeated failed authentication attempts.

        This rule detects whether the same username receives multiple
        failed login attempts within a defined time window.
        """

        if log.get("event_type") != "ssh_failed_login":
            return

        username = log.get("username")

        if not username:
            return

        event_time = log["timestamp"]

        # Store failed attempt for the affected username.
        self.failed_events_by_user[username].append({
            "timestamp": event_time,
            "log": log
        })

        # Remove failed attempts outside the configured time window.
        self.failed_events_by_user[username] = self.cleanup_events(
            events=self.failed_events_by_user[username],
            current_time=event_time,
            timeframe=self.repeated_failed_timeframe
        )

        if len(self.failed_events_by_user[username]) >= self.repeated_failed_threshold:
            self.generate_alert(
                rule_name="Repeated failed authentication attempts",
                description=(
                    f"{len(self.failed_events_by_user[username])} failed "
                    f"authentication attempts for user '{username}' within "
                    f"{self.repeated_failed_timeframe} seconds"
                ),
                log=log
            )

    def detect_ip_based_login_analysis(self, log):
        """
        Performs IP-based login analysis.

        This rule detects whether a single IP address attempts to
        authenticate with multiple different usernames within a defined
        time window.
        """

        ip = log.get("ip")
        username = log.get("username")

        if not ip or not username:
            return

        event_time = log["timestamp"]

        # Store username attempted from the source IP.
        self.usernames_by_ip[ip].append({
            "timestamp": event_time,
            "username": username,
            "log": log
        })

        # Remove outdated attempts outside the time window.
        self.usernames_by_ip[ip] = self.cleanup_events(
            events=self.usernames_by_ip[ip],
            current_time=event_time,
            timeframe=self.ip_user_timeframe
        )

        # Count unique usernames attempted from this source IP.
        unique_users = {
            event["username"]
            for event in self.usernames_by_ip[ip]
        }

        if len(unique_users) >= self.ip_user_threshold:
            self.generate_alert(
                rule_name="IP-based login analysis",
                description=(
                    f"Source IP attempted authentication for "
                    f"{len(unique_users)} different usernames within "
                    f"{self.ip_user_timeframe} seconds"
                ),
                log=log
            )

    def detect_suspicious_login(self, log):
        """
        Detects suspicious login behavior.

        This rule identifies successful logins outside the expected
        login time range.
        """

        if log.get("event_type") != "ssh_successful_login":
            return

        event_time = log["timestamp"]

        # Extract the hour from the actual log timestamp.
        hour = event_time.hour

        if hour < self.allowed_login_start_hour or hour >= self.allowed_login_end_hour:
            self.generate_alert(
                rule_name="Suspicious login behavior",
                description=(
                    f"Successful login outside expected time range "
                    f"({self.allowed_login_start_hour}:00 - "
                    f"{self.allowed_login_end_hour}:00)"
                ),
                log=log
            )

    def cleanup_events(self, events, current_time, timeframe):
        """
        Removes outdated events from a list.

        This method implements a sliding-window mechanism based on
        the actual timestamps extracted from the log data.

        Parameters:
            events (list):
                Stored events for a specific grouping key.

            current_time (datetime):
                Timestamp of the currently processed log event.

            timeframe (int):
                Maximum age of events in seconds.

        Returns:
            list:
                Events that are still inside the configured time window.
        """

        return [
            event
            for event in events
            if (current_time - event["timestamp"]).total_seconds() <= timeframe
        ]

    def generate_alert(self, rule_name, description, log):
        """
        Generates a detection output.

        The alert contains contextual information about the event and
        the triggered rule.

        Parameters:
            rule_name (str):
                Name of the triggered detection rule.

            description (str):
                Explanation of why the rule was triggered.

            log (dict):
                Structured log event that caused the alert.
        """

        print(
            f"[ALERT] {rule_name} | "
            f"Time: {log.get('timestamp_iso')} | "
            f"User: {log.get('username')} | "
            f"IP: {log.get('ip')} | "
            f"Event: {log.get('event_type')} | "
            f"Description: {description}"
        )
